# Config settings
title: BDR kodebok
author: BDR

description: "Denne siden inneholder alle variabler og variabel verdi i
Nasjonalt medisinsk kvalitetsregister for barne- og ungdomsdiabetes (BDR) databasen"
baseurl: "/kodebok"

# Revidert dato generelt
dato: "30-01-2019"

# Hjem
hjemtitle: Hjem
hjemurl: https://bdreg.github.io/bdrkodebok

# Collections settings
collections:
  koder:
    output: true
    permalink: /:name/

# Search settings
tipue_search:
  include:
    pages: true
    collections: [koder]
  exclude:
    files: [index.md, search.html, about.md]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
date_format: "%b %-d, %Y"
