# Config settings
title: BDR kodebok
author: BDR
description: Liste over alle variablene og variableverdi i BDR database
baseurl: "/kodebok"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html, about.md]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
date_format: "%b %-d, %Y"
