# Config settings
title: BDR kodebok
description: Liste over alle variablene og koder i BDR
baseurl: "/kodebok"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html, about.md]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Searchable optimization
plugins:
  - jekyll-seo-tag
